### ISSUE TITLE
Using PyAlexa-Skill package to create a python Alexa Skill: error when trying to run skill.

### ISSUE THREAD

**Issue by borograham** [youngsoul/PyAlexa#3]
Probably me that has done something wrong! All help appreciated.

Still working through your video. When I try a test utterance, the Amazon Test Console gives me:

'The remote endpoint could not be called, or the response it returned was invalid.' 

When I look at the AWS log, I see:

Unable to import module 'main': No module named pyalexaskill.AlexaBaseHandler

I think the Python engine in Lambda is looking for the modules install on my Mac by 'pip install alexa skill'. Do I need to include these files in my ZIP file?﻿

**Comment by youngsoul** [comment]
Can you have a look at this test project that was built with the latest library: 0.2.6
https://github.com/youngsoul/PyAlexaSkillTest

In your project do you have a requirements.txt file like the one specified here?

Also, when you setup the AWS lambda, by default the entry point it looks for is:  

lambda_function.lambda_handler

you have to change this to be main.lambda_handler

last thing to check is your command line to build the zip file.  It should look like:

create_aws_lambda.py -i "MyAlexaHandler.py,main.py,some_other_util.py"

notice the command line include a list of all of the python files to include in the zip, including main.py.  

if you unzip the file in the deployments directory, all of the files you expect to be uploaded should be there.

**Comment by borograham** [comment]
Brilliant! That worked. Many thanks.
